### ISSUE TITLE
Break can hang if window not visible

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#258]
The original issue #245 has been mostly fixed but there are edge cases where this can still happen.
Would be good to make this completely reliable.

**Comment by psiinon** [comment]
@dscrobonia do you think this should be fixed now?

**Comment by dscrobonia** [comment]
I think this particular issue is fixed, but only because we've hacked around it to automatically push messages through that arrive before the HUD is loaded. So that's still not correctly handled, and that is what this ticekt is supposed to reflect IIRC

**Comment by scalefree** [comment]
How is this issue fixed? I'm working through the HUD tutorial & cannot even complete it because of Break being broken (as described in 245 - I tried to follow the method used there to bypass the broken Break but couldn't get it to work). If there's a workaround I can use it needs to be better documented than it is now.
