### ISSUE TITLE
New tool - enable / disable favorite script

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#335]
OK, not a trivial first issue, so maybe a good second one?
This would add a tool similar to the one demo'ed by @dscrobonia on https://segment.com/blog/hacking-with-a-heads-up-display (section 3)
In this case there would need to be an option to choose which script to enable / disable - the list of ones installed should already be available via the API.
So when the user first clicks on the tool they'd get a dialog to choose which script from a pull down, then clicking on the tool would toggle the script on and off, and right clicking it would give the option to change script.

**Comment by michaelgabrielinfosec** [comment]
Hey psiinon, just want to double-check before I start contributing. 

The basic functionality for this feature would be to have a button that, when clicked, would display some kind of menu containing a list of all the installed scripts and have some kind of toggle to enable/disable each of them. 

If that's correct, would it be alright to place the initial button on the "Select Tool" menu underneath the "Show HTML Report" feature?

**Comment by shamashel** [comment]
Any requirements regarding which scripts should be displayed (ex: don't display scripts with type hud)? Also, should we display their entire name as per API (ex: "tools/spider.js") or try to parse out the text between the last instance of a slash and first instance of a period?

**Comment by shamashel** [comment]
Am I correct in assuming we should leave out any scripts with an engine of "Null" or that do not have an "enabled" value?

**Comment by psiinon** [comment]
@shamashel yeah, that sounds reasonable.
Do you fancy working on this?

**Comment by shamashel** [comment]
Definitely.

**Comment by psiinon** [comment]
Great - I've assigned it to you :) Let us know if you have any questions.

**Comment by thc202** [comment]
Why not include scripts with null engine?

**Comment by shamashel** [comment]
Scripts added by users should always have an engine of either Oracle Nashorn or Mozilla Zest and an "enabled" value of true or false. On the flip side, all scripts for zap-hud have both a null engine and undefined "enabled" value. Not including scripts that have either a null engine or undefined "enabled" value would mean that only user scripts are displayed.

Please correct me if I'm wrong here, as I've only ever used scripts to add active scan rules so far.

**Comment by psiinon** [comment]
We also support Python, Ruby and Groovy scripts via add-ons on the Marketplace.
But they will all have an 'enabled' value is relevant.

**Comment by thc202** [comment]
If you don't want to show HUD scripts (which makes sense for this tool) you can just ignore the ones with `hud` type. There are other script types with null engine that are added by the user and can be enabled.

**Comment by shamashel** [comment]
Cool, didn't realize other languages were supported. Thanks for the info! I'll filter on enabled just in case there are other builtin scripts without the `hud` type.

**Comment by shamashel** [comment]
I've added in the tool & right-click to choose script functionality on my fork. Going to work on the left-click to enable/disable next.

Quick question: when the user first adds the tool to a panel, should it display a modal to select the initial script **before** being added to the panel, or should it display said modal after the user left/right clicks on the tool (in the panel) for the first time?

Asking because I'd probably need a few follow-up questions if it's the first option.

**Comment by psiinon** [comment]
I'm happy with the modal being displayed after the user clicks on the tool for the first time.
The other option would probably require some infrastructure changes, so could be added later on.

**Comment by shamashel** [comment]
I pretty much completed the feature, but I'm running into one last issue. Is there a way to update the tool's label on a panel? I'm currently using `utils.messageAllTabs` with `action: "broadcastUpdate"`, which appears to call the `updateButton` event in `panel.js`, but that only appears to update the `name`, `data`, `icon` and `isDisabled` properties of the tool in the GUI. Currently, I'm working around this by setting the `data` to the script name, but I'm not sure if that would support longer script names.

Is there a different action I should be using for this, would it be alright for me to make changes to the event in order to support the changing of labels, or is it alright to integrate this feature as is?

**Comment by shamashel** [comment]
Should I just leave the feature as-is and make a pull request?

**Comment by thc202** [comment]
In either case feel free to open the PR (it does not need to be all finished).

**Comment by shamashel** [comment]
Which branch should I push it to? The only ones outside of the main branches available are Issue#200 and the dependabot branch

**Comment by kingthorin** [comment]
Just push to origin (from your local feature branch), then open a PR.

**Comment by psiinon** [comment]
Thanks for working on this @shamashel - looking forward to it :)
