### ISSUE TITLE
Add option to clear history / websockets tab

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#411]
This would allow users to ignore older messages they are no longer interested in.

**Comment by shamashel** [comment]
Would it be alright if I started working on this?

**Comment by psiinon** [comment]
@shamashel absolutely :)
I was thinking we would add buttons in the relevant tools bars for the tabs, but feel free to suggest anything else.

**Comment by shamashel** [comment]
To confirm, when we're talking about "clearing" the tab, do you want the actual messages to be deleted, or should they just be hidden in the HUD?

If we are talking about deleting the messages; which API would you recommend using? The closest thing I found was `deleteSiteNode` in core, since deleting a node will also delete all the relevant requests.

**Comment by psiinon** [comment]
Yeah, I was thinking this would just hide the messages in the HUD rather than remove them from ZAP. The HUD caches the history messages so hopefully it shouldnt be too hard.

**Comment by Vitika9** [comment]
@psiinon may I work on this? 🙂

**Comment by psiinon** [comment]
@Vitika9 you can!
Let us know how you get an and if you have any problems setting your develepment environment up - the HUD is a bit complex and no one is focussing on it right now. However it would be very good to have someone working on it 😁
