### ISSUE TITLE
the HUD is blocking view of lower tabs

### ISSUE THREAD

**Issue by dannaksan12** [zaproxy/zap-hud#552]
we are using a tool to switch between experiment and toggle states on the website which is being found at the bottom of the browser. this is being covered over by the HUDs history and websockets tab. It is making testing more difficult. Is there a way to hide/unhide the lower HUD tab when needed?
Browser used: Chrome on Windows 10.

**Comment by psiinon** [comment]
Thanks for reporting this.
@dannaksan12 is the tool you are using is always at the bottom of the page when the HUD isnt being used? What happens when you expand the HUD lower tabs? Is it completely hidden by them?
If thats the case then we would need to hide the HUD lower frame.
One option would be to resize it to just show the HUD / config buttons on the bottom right when HUD button is pressed.
I quite like that idea as thats how we hide the side frames too. We might need to hide / disable the expand arrow when thats been pressed.

**Comment by dscrobonia** [comment]
> One option would be to resize it to just show the HUD / config buttons on the bottom right when HUD button is pressed.

Ah that would be nice. so that the Hide button hides the side frames and pulls the bottom bar into one corner. That would be a good addition to that feature.

On top of that, however, we should see if there is any way we can better display the bottom bar so that its not covering things. I don't think it will always be possible, but there may be some more things we can do to the target window.

**Comment by dannaksan12** [comment]
@psiinon it will always be at the bottom and even if its not expanded it is still covering the tool completely so there is no way to use it.
It would be really good if it could be resized similar to the side panel - especially if someone needs to test the footer for whatever reason as I would suspect that would be covered by the HUD too.

**Comment by psiinon** [comment]
Agreed - I think we need to hide the lower tabs when we hide the HUD.
I have a poc that does this, but its definitely not robust enough for a PR yet ;)
